### ISSUE TITLE
Alternate example to use folding-cell programmatically?

### ISSUE THREAD

**Issue by JesusAdolfo** [Ramotion/folding-cell#106]
I've seen the example on how to use folding-cell programmatically, however, I would prefer not having to use easyPeasy in the project to make it work.. I tried doing it both natively and with a pod that I've been using called LBTAComponents but I keep getting the error

`fatalError("set constratins outlets")`

and I don't know why. I am trying to replicate the programmatic example...

For instance, I am doing this for the container view:

```
func createContainerView() -> UIView{
        let containerView : UIView = {
            let view = UIView()
            view.backgroundColor = .red
            view.translatesAutoresizingMaskIntoConstraints = false
            return view
        }()
        contentView.addSubview(containerView)
        
        let anchors = containerView.anchorWithReturnAnchors(topAnchor, left: leftAnchor, bottom: nil, right: rightAnchor, topConstant: 10, leftConstant: 10, bottomConstant: 10, rightConstant: 10, widthConstant: 10, heightConstant: CGFloat(75 * itemCount))
        
        print(anchors.first)
        print(anchors.first?.constant)
        
        let topConstraint = anchors.first
        topConstraint?.identifier = "ContainerViewTop"
        
        containerView.layoutIfNeeded()
        return containerView
    }
```

I've tried setting the constraints and the identifier natively but that didn't work. Could someone provide an example on how to do that? I'm trying to stay away from storyboards...

**Comment by Jauzee** [comment]
@JesusAdolfo seems like you're trying to setup views with `Layout Anchors`, but `FoldingCell` was designed to use `Layout Constraints`. Maybe it'll be easier to you to use xibs or storyboards. Look at the [demo project](https://github.com/Ramotion/folding-cell/tree/master/FoldingCell/FoldingCell-Demo).
