### ISSUE TITLE
Shame for demonstration example and support.

### ISSUE THREAD

**Issue by qsdnino** [Ramotion/folding-cell#110]
It is better to close this repo than to keep it alive with this poor tutorial and support.

**Comment by Jauzee** [comment]
@qsdnino oh, your first issue on Github is so strict. There are a lot of open-source projects maintained by Ramotion on Github and it's very time consuming work. 
Keep in mind that you can contribute to open-source projects & ask for help, but you can't demand something. 

We was very busy and missed a lot of issues here, but now we'll try to figure out all of them.

**Comment by qsdnino** [comment]
Sorry for inconvenience. I had deadline for one project and found your cell very intresting for implementation in my app. I lost some time trying to make cell works. I was under stressa with deathline and dissapointed with cell code deprecation and lack of documentation and better example tutorial. I think you could have many many more users if you make better tutorial and swift 3 support. 
Sorry once again for inconvenience. If I could contribute in some way please say me how. 

Regards

Nikola Jovic
iOS Developer
QSD BiH d.o.o.
Dr. Ante Starčevića bb, zgrada "Integra"
88000 Mostar
Tel:+387 (0) 36 316 571 (in process)
Mob:+387 (0) 63 492 521
nino@qsdbih.com
www.qsdbih.com (under construction)
 
 
This email and any files transmitted with it are confidential. If you have received
this email in error please notify the sender and then delete it immediately.
Please note that any views or opinions presented in this email are solely those
of the author and do not necessarily represent those of Company.
 
The recipient should check this email and any attachments for the presence
of viruses. Company accepts no liability for any damage caused by any virus
transmitted by this email.
 
Company may regularly and randomly monitor outgoing and incoming emails
(including the content of them) and other telecommunications on its email
and telecommunications systems. By replying to this email you give your
consent to such monitoring.
 
Save resources: think before you print.
