### ISSUE TITLE
override func animationDuration does not work anymore

### ISSUE THREAD

**Issue by yarodevuci** [Ramotion/folding-cell#112]
After running pod updates function override func animationDuration is no longer valid?

UPDATE: Looks like it was fixed. Thanks guys!

**Comment by yarodevuci** [comment]
I had to manually inserted the code. Pod update did not helped

**Comment by Jauzee** [comment]
@yarodevuci please try 2.1.1 version. Just pushed update.

**Comment by Jauzee** [comment]
@yarodevuci did it resolve the issue?

**Comment by yarodevuci** [comment]
Yes. Thank you! @Jauzee
