### ISSUE TITLE
Have all views open by default 

### ISSUE THREAD

**Issue by JorgeAGomez** [Ramotion/folding-cell#113]
I am wondering if there is any way to have all cell views open when entering the view controller that contains the folding cells? 

Is there a way to simulate the "tap" that opens the cell programmatically?

**Comment by Jauzee** [comment]
@JorgeAGomez if you setup `folding-cell` as in demo project you will simply need to fill `cellHeights` array with `kOpenCellHeight`:

```swift
cellHeights = Array(repeating: kOpenCellHeight, count: kRowsCount)
```

**Comment by JorgeAGomez** [comment]
@Jauzee Oh that was easy. :) It worked perfectly! Thank you so much. I don't know why I didn't think about that. 

Loving this folding-cell repo. 👍

**Comment by Jauzee** [comment]
@JorgeAGomez you're welcome!
