### ISSUE TITLE
Folding Cell when I touch the other cell

### ISSUE THREAD

**Issue by henrykapostel** [Ramotion/folding-cell#115]
I am going to implement the tableview using this library.
How can I folding the previous cell when I select the other cell?

**Comment by FelipeMac01** [comment]
hello friend!, im with the same doubt you, did you get how to close the previous cells when it open a new one? @henrykapostel

**Comment by FelipeMac01** [comment]
here is the solution @henrykapostel : 

https://github.com/Ramotion/folding-cell/issues/116
