### ISSUE TITLE
Just one Cell Open

### ISSUE THREAD

**Issue by FelipeMac01** [Ramotion/folding-cell#116]
Hello!

Thanks for this great work, but i would like to ask, if is there a way to programmatically close all folding cell and remain open just the selected cell.

if i click in one cell it opens, if i click in another cell it will open and the last one will close, i would like to add this behavior if it is possible.

Thanks!

**Comment by Jauzee** [comment]
Hi @FelipeMac01 

Received your email. Here I'll give a sample project: 
[FoldingCell.zip](https://github.com/Ramotion/folding-cell/files/1116439/FoldingCell.zip)

**Comment by FelipeMac01** [comment]
Thanks man, it works like a charm! ;)
