### ISSUE TITLE
Rotated Views Not Folding

### ISSUE THREAD

**Issue by theraad** [Ramotion/folding-cell#119]
Hi, I can't seem to get my cells to fold using the animation. I have a cell with a foreground view height of 162 and a container view containing 3 items. The Container view is of height 342, with it's sub containers of height 126, 126 and 90. I've set the item count to be 3 through the interface builder but the cells just dont do the animation. 

![screen shot 2017-07-14 at 3 27 09 pm](https://user-images.githubusercontent.com/28601705/28212192-f02e21b6-68a8-11e7-826f-1b7e1488d6f6.png)
![screen shot 2017-07-14 at 3 22 11 pm](https://user-images.githubusercontent.com/28601705/28212191-f02c7744-68a8-11e7-92ec-08f0b8188ac4.png)

Also i've set up the constraints similarly to the demo app, where we have trailing, leading, height and a top to the overall container view. 

Could you let me know what i am missing?

**Comment by ober01** [comment]
Follow this steps https://github.com/Ramotion/folding-cell#usage
