### ISSUE TITLE
fatal error: set identifier: file FoldingCell.swift

### ISSUE THREAD

**Issue by gohlance** [Ramotion/folding-cell#12]
I am getting the above mentioned error, seems like a method, configureDefaultState(), within FoldingCell.swift, is checking for "ForegroundViewTop" and "ContainerViewTop".

Maybe clearer documentation on how to add those 2 in the storyboard.

**Comment by gohlance** [comment]
<img width="1024" alt="screen shot 2016-02-11 at 1 04 39 am" src="https://cloud.githubusercontent.com/assets/6783626/12954911/8dec24da-d05b-11e5-871f-6f43e518d110.png">

Adding screenshot for reference

**Comment by ober01** [comment]
add video https://vimeo.com/154954299 to readme.md
I hope this help

**Comment by fbarraganef** [comment]
I doing this in a programatically way. In fact I'm also using easypeasy like the example, but I always getting the error set ForegroundViewTop or ContainerViewTop constraint.

I update the code: 

extension DemoFoldingCell {
    
    private func createForegroundView() -> RotatedView {
        let foregroundView =  RotatedView(frame: .zero)
        foregroundView.backgroundColor = UIColor.red
        foregroundView.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(foregroundView)
        
        foregroundView.easy.layout(
            Height(75),
            Left(8),
            Right(8)
        )
        let constraint = foregroundView.easy.layout( Top(8).to(self, .top) ).first
        constraint?.identifier = "ForegroundViewTop"
        foregroundView.layoutIfNeeded()
        
        return foregroundView
    }
    
    private func createContainerView() -> UIView {
        let containerView = UIView(frame: .zero)
        containerView.backgroundColor = UIColor.green
        containerView.translatesAutoresizingMaskIntoConstraints = false
        contentView.addSubview(containerView)
        
        containerView.easy.layout(
            Height(CGFloat(75 * itemCount)),
            Left(8),
            Right(8)
        )
        
        let constraint = containerView.easy.layout( Top(8).to(self, .top)  ).first
        constraint?.identifier = "ContainerViewTop"
        containerView.layoutIfNeeded()
        
        return containerView
    }
}


Thanks
Francisco

**Comment by iOSDias** [comment]
@fbarraganef  I rewrite code like you but have an issue on this line:
fatalError("set foregroundViewTop or containerViewTop outlets in storyboard")
How you solve it?
