### ISSUE TITLE
Issue on cell select Animation

### ISSUE THREAD

**Issue by ItsMeMIHIR** [Ramotion/folding-cell#120]
`if cellIsCollapsed {
            cellHeights[indexPath.row] = kOpenCellHeight
            cell.selectedAnimation(true, animated: true, completion: nil)
            duration = 0.5
        } else {
            cellHeights[indexPath.row] = kCloseCellHeight
            cell.selectedAnimation(false, animated: true, completion: nil)
            duration = 0.8
        }`

it shows  "selectedAnimation" method is deprecated.

**Comment by jakupKnudsen** [comment]
Replace `selectedAnimation` with `unfold`.

**Comment by ItsMeMIHIR** [comment]
how to implement `unfold`
