### ISSUE TITLE
Move scroll position of table view to the open cell

### ISSUE THREAD

**Issue by tbalancin** [Ramotion/folding-cell#121]
Hello Guys,

If the cell that I will open is off the screen should move the scroll to show all the cell.

For example in the screen shot attached, the cell number 3 it's cutting on the half, once I open it, should show all the cell automatically.

Could you please help me?

![captura de tela 2017-08-15 as 17 56 54](https://user-images.githubusercontent.com/513637/29336213-73269a1e-81e3-11e7-8886-850233541fae.png)
![captura de tela 2017-08-15 as 17 58 50](https://user-images.githubusercontent.com/513637/29336201-6e356ad0-81e3-11e7-815b-6c6ecfa8c251.png)

![captura de tela 2017-08-15 as 17 56 46](https://user-images.githubusercontent.com/513637/29336193-690e6282-81e3-11e7-8b79-95d311133ee5.png)

**Comment by dariolr** [comment]
Try to add this line at the end of didSelectRowAt indexPath method 

tableView.scrollToRow(at: indexPath, at: UITableViewScrollPosition.top, animated: true)
