### ISSUE TITLE
while fold and unfold - table cell framing or scrolling issue

### ISSUE THREAD

**Issue by Rathish11** [Ramotion/folding-cell#124]
While opening and closing the cell some times the whole cells in tableview moves up and coming down. Any one have solution for this.

**Comment by wudifeixia** [comment]
Me too!, I am so confused. Does anyone know what is wrong? I have checked all my codes and the key part is almost the same as the example.

**Comment by sergiusX** [comment]
Me too

**Comment by sergiusX** [comment]
just delete this code:
 //tableView.estimatedRowHeight = kCloseCellHeight
 //tableView.rowHeight = UITableViewAutomaticDimension

**Comment by wudifeixia** [comment]
Thank you for helping me. But I have already deleted this code. My program just won't work as the example does.

**Comment by sergiusX** [comment]
I deleted this code and my program works well.
In the example there is the same problem, try to open the last cell in the table and you will see.
sorry for my English.

**Comment by mahmutpinarbasi** [comment]
In my case, adding these lines fixed the problem.

```
tableView.estimatedRowHeight = kCloseCellHeight
tableView.rowHeight = UITableViewAutomaticDimension
```
