### ISSUE TITLE
project is not archeiving with folding cell

### ISSUE THREAD

**Issue by tusharjindal353** [Ramotion/folding-cell#127]
"FoldingCell.FoldingCell.containerView.setter : weak __ObjC.UIView!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.containerViewTop.getter : weak __ObjC.NSLayoutConstraint!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.containerViewTop.materializeForSet : weak __ObjC.NSLayoutConstraint!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.foregroundView.getter : weak FoldingCell.RotatedView!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.containerViewTop.setter : weak __ObjC.NSLayoutConstraint!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.foregroundViewTop.getter : weak __ObjC.NSLayoutConstraint!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.foregroundView.setter : weak FoldingCell.RotatedView!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.foregroundViewTop.materializeForSet : weak __ObjC.NSLayoutConstraint!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.containerView.materializeForSet : weak __ObjC.UIView!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.foregroundView.materializeForSet : weak FoldingCell.RotatedView!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.itemCount.setter : Swift.Int", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.backViewColor.materializeForSet : __ObjC.UIColor", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.itemCount.materializeForSet : Swift.Int", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.itemCount.getter : Swift.Int", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.backViewColor.getter : __ObjC.UIColor", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.durationsForCollapsedState.materializeForSet : [Swift.Double]", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.backViewColor.setter : __ObjC.UIColor", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.containerView.getter : weak __ObjC.UIView!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.durationsForCollapsedState.setter : [Swift.Double]", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.isUnfolded.materializeForSet : Swift.Bool", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.durationsForExpandedState.getter : [Swift.Double]", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.durationsForExpandedState.setter : [Swift.Double]", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.durationsForCollapsedState.getter : [Swift.Double]", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.durationsForExpandedState.materializeForSet : [Swift.Double]", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.isUnfolded.getter : Swift.Bool", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.isUnfolded.setter : Swift.Bool", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
  "FoldingCell.FoldingCell.foregroundViewTop.setter : weak __ObjC.NSLayoutConstraint!", referenced from:
      _OBJC_CLASS_$__TtC10Book_a_Cab8DemoCell in DemoCell.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ober01** [comment]
Showroom contains the FoldingCell lib and it on AppStore https://itunes.apple.com/app/apple-store/id1182360240
