### ISSUE TITLE
Crashing on animations

### ISSUE THREAD

**Issue by hyunsbuns** [Ramotion/folding-cell#13]
I'm a novice programmer, but I'm pretty sure I'm doing all the steps right... keeps crashing when selecting the rotated view: "fatal error: Array index out of range"

All the breakpoints seem to be happening on animation lines:

> #2	0x00000001002eb878 in FoldingCell.openAnimation(completion : () -> ()?) -> () at /Users/Brabble/Documents/Squad/Pods/FoldingCell/FoldingCell/FoldingCell/FoldingCell/FoldingCell.swift:318
> #3	0x00000001002ea948 in FoldingCell.selectedAnimation(Bool, animated : Bool, completion : () -> ()?) -> () at /Users/Brabble/Documents/Squad/Pods/FoldingCell/FoldingCell/FoldingCell/FoldingCell/FoldingCell.swift:237
> #4	0x00000001000d2930 in DemoTableViewController.tableView(UITableView, didSelectRowAtIndexPath : NSIndexPath) -> () at /Users/Brabble/Documents/Squad/Squad/DemoTableViewController.swift:67

Am I missing something?

**Comment by ober01** [comment]
step 6) durations count must be equal it itemCount

**Comment by hyunsbuns** [comment]
YES! Thanks!
