### ISSUE TITLE
fatal error: set constrains outlet (foregroundViewTop and ContainerViewTop)

### ISSUE THREAD

**Issue by Tomm89** [Ramotion/folding-cell#131]
Hi guys! Thanks so much for great library, but i am getting this error and I dont know why.
I`ve set the identifiers and constrains the same way as in video, but still same issue.

Thank you for your solution! :)

**Comment by Just66** [comment]
Had the same issue, check if you have other cells attached to the same class, which inherits FoldingCell

**Comment by jacobo360** [comment]
Seems like they are not using camelCase on the video, but naming with CapsOnTheFirstLetter.. Which contradicts their instructions.

**Comment by hoyelam** [comment]
You have to connect the outlet from the FoldingCell to the constraint. You can do this by control click-drag to the constraint (foregroundViewTop, containerViewTop. The video only shows how to set the constraints, but you also have to connect the outlets.
