### ISSUE TITLE
shake when unfolding second cell

### ISSUE THREAD

**Issue by yehot** [Ramotion/folding-cell#134]
Issue：
shake when unfolding second cell

Step:
1. unfold cell in indexPath[0]
2. scroll that cell out of screen
3.  unfold another cell ，all tableview cell  shake obviously，and  shake only once

See The Video：
https://youtu.be/OnVzf8jLHKo

**Comment by krema** [comment]
The reason for that is the refresh of the tableView (beginUpdates, endUpdates)

Can you try following (untested):

    foldingCell.unfold(true, animated: true, completion: {() in
        self.tableView.reloadRows(at: [indexPath], with: .none)
    })

**Comment by Juriv** [comment]
This is standard behavior of tableView.
