### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [Ramotion/folding-cell#135]
Hi,
I have a different requirement for folding as I need to do horizontal scroll and click on any items it should unfold that.
So my question is how it can work with the collection view to fit with my requirement.
Any suggestion would be appreciated.

Thanks,
Rahul

**Comment by ober01** [comment]
Hi, Folding-CollectionCell is a nice idea. In future, we will implement in the new repository.
