### ISSUE TITLE
Request button action is empty

### ISSUE THREAD

**Issue by shameer49** [Ramotion/folding-cell#136]
Please add request button action. In the gif Request button action is working but in the code i cannot find any action for that, just 

  
  @IBAction func buttonHandler(_ sender: AnyObject) {
    print("tap")
  }

**Comment by krema** [comment]
You can make a pull request?

**Comment by shameer49** [comment]
I don't have a fix for the solution.

**Comment by shameer49** [comment]
But i don't have a solution for this

**Comment by amervil** [comment]
I have a solution to know what button was pressed:

- Connect the UIButton to DemoCell.swift
@IBOutlet weak var button: UIButton!

- In MainTableViewController.swift, give a tag number to the button:
override func tableView(_: UITableView, willDisplay cell: UITableViewCell, forRowAt......) {
..
..
..
cell.button.tag = indexPath.row
}

- In DemoCell.swift, ask for the tag when the button is pressed:
@IBAction func buttonHandler(_ sender: UIButton) {
print("tap: ", sender.tag)
}

Now you know the row of the cell where the button was pressed

**Comment by ober01** [comment]
Folding-Cell supported only folding animation
