### ISSUE TITLE
Folding Cell with Map View issue

### ISSUE THREAD

**Issue by talis00051** [Ramotion/folding-cell#140]
I have made a folding cell with a mapview inside the container view. It is all okay when I just open one folding cell in the tableview, however if I open more than one folding cells, the maps will be gone after scrolling even if I close all the cells and reopen them.

The animation will become weird too, which does not fold again.

**Comment by igork-ramotion** [comment]
The first idea that you need to update your cell data or state after dequeue. To get more accurate advice you can provide code with example that describes your case
