### ISSUE TITLE
Folding-cell demoObjectiveC cant compile

### ISSUE THREAD

**Issue by bfjfm2** [Ramotion/folding-cell#144]
Awesome Demo.  It has an issue in objectiveC Demo. How to fix this issues?

/User/folding-cell/FoldingCell/FoldingCell-DemoObjc/TableViewController.m:62:27: No visible @interface for 'FoldingCell' declares the selector 'selectedAnimation:animated:completion:'

/User/folding-cell/FoldingCell/FoldingCell-DemoObjc/TableViewController.m:64:27: No visible @interface for 'FoldingCell' declares the selector 'selectedAnimation:animated:completion:'

/User/folding-cell/FoldingCell/FoldingCell-DemoObjc/TableViewController.m:88:9: No visible @interface for 'FoldingCell' declares the selector 'setDurationsForExpandedState:'

/User/folding-cell/FoldingCell/FoldingCell-DemoObjc/TableViewController.m:89:9: No visible @interface for 'FoldingCell' declares the selector 'setDurationsForCollapsedState:'

/User/folding-cell/FoldingCell/FoldingCell-DemoObjc/TableViewController.m:111:11: No visible @interface for 'FoldingCell' declares the selector 'selectedAnimation:animated:completion:'

/User/folding-cell/FoldingCell/FoldingCell-DemoObjc/TableViewController.m:115:11: No visible @interface for 'FoldingCell' declares the selector 'selectedAnimation:animated:completion:'

**Comment by WildDylan** [comment]
same question

**Comment by bfjfm2** [comment]
@WildDylan They haven't updated those methods and properties with @objc for Objective C Accessible.  You just replace the attached file. It will work.
[FoldingCellFixForObjectiveC.zip](https://github.com/Ramotion/folding-cell/files/1957867/FoldingCellFixForObjectiveC.zip)

**Comment by WildDylan** [comment]
very thanks

**Comment by bfjfm2** [comment]
@0ber  Amazing work. Sure, I will do next time.
