### ISSUE TITLE
ERROR: Invalid update: invalid number of rows in section 0

### ISSUE THREAD

**Issue by coinmagic** [Ramotion/folding-cell#145]
I try to use search bar in my application. After filtering, I update the table (tableView.reloadData) and also update the number of row in section according to the number of filtered items. I also update the kRowsCount

After filtering (from 11 items) to 3 items, I got the error when I tap on the row

'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (11) must be equal to the number of rows contained in that section before the update (4), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) 

The error is from 

tableView.beginUpdates()
tableView.endUpdates()

**Comment by 0ber** [comment]
https://stackoverflow.com/questions/21870680/invalid-update-invalid-number-of-rows-in-section-0
