### ISSUE TITLE
Error: "contanerView.height too high"

### ISSUE THREAD

**Issue by augustocadini** [Ramotion/folding-cell#146]
I did exactly what is described in the tutorial, I also downloaded the example and compared the codes, when I click on a cell the following error occurs:

`Thread 1: Assertion failed: contanerView.height too high`

On the class: FoldingCell
Line: `220:         assert(containerViewSize.height - 2 * foregroundViewSize.height == 0, "contanerView.height too high")`

**Comment by 0ber** [comment]
<img width="1758" alt="image 2018-04-26 at 10 26 36 am" src="https://user-images.githubusercontent.com/5435782/39291672-72c1d20c-493c-11e8-82b5-70c1b6f3e025.png">

**Comment by augustocadini** [comment]
The constraint height has been seted. 

![captura de tela 2018-04-26 as 12 29 28](https://user-images.githubusercontent.com/18659348/39315614-7dff35f4-494d-11e8-8531-3cc8a6fa414f.png)

**Comment by 0ber** [comment]
Set ItemCount to 3 in your FoldingCell

**Comment by chadbrochill317** [comment]
How do you set the item count?
