### ISSUE TITLE
cornerRadius + Shadow layer

### ISSUE THREAD

**Issue by ReeceHumphreys** [Ramotion/folding-cell#148]
Is there any way of accomplishing a rounded `RotatingView` with a drop shadow? The traditional method of using two views, one with the shadow layer and one with the `cornerRadius` set will not work. There seems to be a white UIView that gets created and requires masking out with this method but doing so will cut off the shadow

**Comment by lovemelong1** [comment]
I also want to know it.

**Comment by s-ilnar** [comment]
me so same interesting
