### ISSUE TITLE
How to get rotated views to fold?

### ISSUE THREAD

**Issue by hyunsbuns** [Ramotion/folding-cell#15]
How do I get the folding animation to happen on multiple views. Right now I have 3 views in the container, and I set the class of the last 2 to Rotated View, and added tags 1 and 2. Then I set the constraints. The animation is only folding once though when it should be folding 3 times. What am I missing?

**Comment by ober01** [comment]
you need set itemCount to 3 

```
@IBInspectable var itemCount: NSInteger = 2 //count of folding 
```

**Comment by hyunsbuns** [comment]
tried that, still 1 fold... and it was set in interface builder

**Comment by ober01** [comment]
need more information, can you make a  screenshots:  your viewcontroller in storyboard and open cell in simulator ?

**Comment by hyunsbuns** [comment]
![screen1](https://cloud.githubusercontent.com/assets/7862052/13069739/ef763ab8-d454-11e5-965d-27f0def48855.jpg)
![screen2](https://cloud.githubusercontent.com/assets/7862052/13069738/ef75c0ba-d454-11e5-84a4-0642765c0d93.jpg)
![screen3](https://cloud.githubusercontent.com/assets/7862052/13069737/ef731a90-d454-11e5-91fe-2e1a57e42a39.jpg)

**Comment by ober01** [comment]
blue view height must be equal purple view height

**Comment by hyunsbuns** [comment]
Thanks that worked... That should be documented somewhere. Appreciate your help.

**Comment by haemi** [comment]
what's the rule here when trying to fold multiple times? in your case: blue view height == purple view height, but what about the light blue one?
