### ISSUE TITLE
Giving Error in FoldingCell.swift file

### ISSUE THREAD

**Issue by aju10** [Ramotion/folding-cell#150]
Error is Value of type '[UIView]' has no member 'compactMap'
changed alot of things but won't work

**Comment by 0ber** [comment]
What swift version do you use?

**Comment by aju10** [comment]
swift 4.0 ,Solved the issue mate, i replaced compactMap with flatMap

**Comment by 0ber** [comment]
It strange, because the `flatMap` is deprecated method, look for documentation https://developer.apple.com/documentation/swift/sequence/2905332-flatmap

**Comment by UniMarkit** [comment]
We also had a similar issue here, @0ber we are using flatMap for now. using swift 4.0 as well

**Comment by aju10** [comment]
@UniMarkit 
Hello @UniMarkit 
update your Xcode to 9.3, then it will support to compactMap.

**Comment by azhararmar** [comment]
Same issue with Swift 4.0, changing to flatMap works.

**Comment by devansh1110** [comment]
Hi, 
When I change compactMaps to flatMaps on line 107 of FoldingCell.swft, it gives me error: 
`Ambiguous use of 'flatMap'`

Please advice 

Thanks,
Devansh
