### ISSUE TITLE
Weird Behavior When Opening and Closing the Cell

### ISSUE THREAD

**Issue by SamaritanMachine** [Ramotion/folding-cell#155]
Hello. 

First of all, folding-cell is great library, thanks everyone.

I followed tutorials and some issue topics. However, my folding cell acts weird behavior. Can anyone guess why is this happening? My storyboard things (constraints and connections and also classes) and code implementations are set like tutorials except one line of code. 

I added `tableView.deselectRow(at: indexPath, animation: false)` in tableView didSelectRowAt method.

Before this code the case was more weird. Anyway, I attached a video which shows the situation. Please help me...  

[https://streamable.com/bc0a7](url)

https://streamable.com/bc0a7

**Comment by SamaritanMachine** [comment]
Can anyone help me ?

**Comment by chadbrochill317** [comment]
I am also having the same issue!

**Comment by 0ber** [comment]
read https://github.com/Ramotion/folding-cell#usage
