### ISSUE TITLE
Set foregroundViewTop or containerViewTop outlets in storyboard

### ISSUE THREAD

**Issue by iOSDias** [Ramotion/folding-cell#156]
I doing this in a programatically way. In fact I'm also using easypeasy like the example, but I always getting the error set ForegroundViewTop or ContainerViewTop constraint.

I update the code:

extension DemoFoldingCell {
private func createForegroundView() -> RotatedView {
    let foregroundView =  RotatedView(frame: .zero)
    foregroundView.backgroundColor = UIColor.red
    foregroundView.translatesAutoresizingMaskIntoConstraints = false
    contentView.addSubview(foregroundView)
    
    foregroundView.easy.layout(
        Height(75),
        Left(8),
        Right(8)
    )
    let constraint = foregroundView.easy.layout( Top(8).to(self, .top) ).first
    constraint?.identifier = "ForegroundViewTop"
    foregroundView.layoutIfNeeded()
    
    return foregroundView
}

private func createContainerView() -> UIView {
    let containerView = UIView(frame: .zero)
    containerView.backgroundColor = UIColor.green
    containerView.translatesAutoresizingMaskIntoConstraints = false
    contentView.addSubview(containerView)
    
    containerView.easy.layout(
        Height(CGFloat(75 * itemCount)),
        Left(8),
        Right(8)
    )
    
    let constraint = containerView.easy.layout( Top(8).to(self, .top)  ).first
    constraint?.identifier = "ContainerViewTop"
    containerView.layoutIfNeeded()
    
    return containerView
}

How to solve it?

**Comment by javorko** [comment]
Hey, try to define containerViewTop and foregroundViewTop inside init, as those two are critical for configureDefaultState() function:


    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        
        containerViewTop = NSLayoutConstraint()
        foregroundViewTop = NSLayoutConstraint()

        containerView = createContainerView()
        foregroundView = createForegroundView()
        commonInit()
    }

It is possible that the error will occur through further implementation of this great framework.
