### ISSUE TITLE
Data are not showing in the table

### ISSUE THREAD

**Issue by pdgoyal** [Ramotion/folding-cell#158]
I am using this pod for my app, But the data are not showing. The table is empty or data are hiding. How can fix it. Thank you.
<img width="720" alt="screen shot 2018-09-10 at 10 02 35 am" src="https://user-images.githubusercontent.com/39942415/45272585-b066c800-b4e0-11e8-9cd8-bc9864ab8b2c.png">

This appeared in my console.

<img width="1061" alt="screen shot 2018-09-10 at 10 20 59 am" src="https://user-images.githubusercontent.com/39942415/45273063-50255580-b4e3-11e8-8284-ef24f59a994c.png">

**Comment by 0ber** [comment]
please read https://github.com/Ramotion/folding-cell#usage
