### ISSUE TITLE
Empty constraints when creating from scratch

### ISSUE THREAD

**Issue by Satchitananda** [Ramotion/folding-cell#16]
When copying FoldingCell from your example projects - everything is fine, but when I'm creating TableView Prototype cells from scratch, adding constraints, it is falling here: https://github.com/Ramotion/folding-cell/blob/master/FoldingCell/FoldingCell/FoldingCell/FoldingCell.swift#L64, as no constraints are found for self.contentView

**Comment by ober01** [comment]
https://vimeo.com/154954299

**Comment by Satchitananda** [comment]
> https://vimeo.com/154954299

Made as in video. self.contentView has empty constraint list.

**Comment by ober01** [comment]
in a video constraints added on contentView and contentView.constraints can't be empty. Check your constraints
