### ISSUE TITLE
UIButton not responding inside ContainerView

### ISSUE THREAD

**Issue by chikiadel** [Ramotion/folding-cell#164]
Hi Ramotion,
 So i have this VC:
![simulator screen shot - iphone xr - 2018-10-18 at 15 00 45](https://user-images.githubusercontent.com/20248810/47160205-5929f380-d2e7-11e8-833c-a48e00c488d6.png)

Red is ContainerView with a UIButton inside (Reminde Me)
Green is ForegroundView

**So my issue is the button dont responding to clicks if those is outside of the foregroundView height otherwise respond correctly **

**Comment by chikiadel** [comment]
NB: Responding area height equal to foregroundHeight

**Comment by Mecan00** [comment]
I solved that problem by adding this line in the awakeFromNib function in my myFoldingCell class: 
containerView.isUserInteractionEnabled = true 
Now everything function as it is supposed to.
