### ISSUE TITLE
Crash while expanding cell

### ISSUE THREAD

**Issue by veer9002** [Ramotion/folding-cell#165]
Getting the crash while tap on the cell to expand. Getting the crash at line number 466 at "self.hiddenAfterAnimation = hidden" in FoldingCell.swift file.

**Comment by wfgilman** [comment]
Figured it out. When setting `foregroundView` to class `RotatedView`, you need to make sure you set the module to `FoldingCell` in interface builder. The exception is being raised because it doesn't know where to find the `hiddenAfterAnimation` property of the `RotatedView` class.
