### ISSUE TITLE
Compilation broken

### ISSUE THREAD

**Issue by githubautomator** [Ramotion/folding-cell#166]
seems foldingcell is broken in Xcode 10 / Mojave

![bildschirmfoto 2018-10-25 um 17 50 58](https://user-images.githubusercontent.com/32924079/47495513-8d208e00-d87e-11e8-9480-afa69a66bf16.png)

![bildschirmfoto 2018-10-25 um 17 13 30](https://user-images.githubusercontent.com/32924079/47495459-67938480-d87e-11e8-8669-72e2e137bc50.png)

**Comment by veer9002** [comment]
You need to unlock this file and make changes manually if you are using cocoapods to install this librabry. Just click on fix it from an error in whole project and after completing all the fixes all the error will gone and you will be able to compile and run the project.
