### ISSUE TITLE
Pulldown not load new data , and button click refresh that page 

### ISSUE THREAD

**Issue by isaacraja15** [Ramotion/folding-cell#168]
Hi sir,
I Have one doubt if i click request button in that expand view and pull down load latest data not showing .

im using alamofire its dynamically generator all cell if i pull down , i have new data mean its need to update ? 

im using tableview.reload? its not working

**Comment by isaacraja15** [comment]
![screenshot 2018-11-07 at 11 11 25 pm](https://user-images.githubusercontent.com/44321070/48149585-7b110780-e2e2-11e8-899c-f91c9db05868.png)

**Comment by isaacraja15** [comment]
![screenshot 2018-11-07 at 11 14 21 pm](https://user-images.githubusercontent.com/44321070/48149788-05596b80-e2e3-11e8-9096-b0884ae65158.png)
![screenshot 2018-11-07 at 11 14 31 pm](https://user-images.githubusercontent.com/44321070/48149808-14401e00-e2e3-11e8-9af1-25b950b3316b.png)
![screenshot 2018-11-07 at 11 14 40 pm](https://user-images.githubusercontent.com/44321070/48149809-14401e00-e2e3-11e8-9cc1-545064ef1d5c.png)
![screenshot 2018-11-07 at 11 14 50 pm](https://user-images.githubusercontent.com/44321070/48149810-14d8b480-e2e3-11e8-8799-78b48aeb2c02.png)
![screenshot 2018-11-07 at 11 14 57 pm](https://user-images.githubusercontent.com/44321070/48149811-14d8b480-e2e3-11e8-9740-c07ffffcd515.png)

**Comment by 0ber** [comment]
FoldingCell is a lib wich add animation for UITableViewCell. It contains the method for setting unselect cell state https://github.com/Ramotion/folding-cell/blob/master/FoldingCell/FoldingCell/FoldingCell.swift#L267.
