### ISSUE TITLE
Weird animation with last cells

### ISSUE THREAD

**Issue by penpens** [Ramotion/folding-cell#169]
Hi,
First of all thanks for this repo 😄 
I just have to report a weird animation with the last cells.
I attach a video of the animation.
Cheers

https://streamable.com/fi0o4

**Comment by PuscaGhenadie** [comment]
Hi penpens,
I had the same issue. The weird animation is more related to the UITableView behaviour, rather than to the folding cell.
This solved my issue - https://forums.developer.apple.com/thread/86703

**Comment by intacto27** [comment]
fix that works for me
if func tableView(didselectrowat...)
in block uiview.animate add next block of code after tableView.endupdates()
"if cell.frame.maxY > tableView.frame.maxY {
                tableView.scrollToRow(at: indexPath, at: UITableView.ScrollPosition.bottom, animated: true)
            }"
