### ISSUE TITLE
Warning report creating from scratch

### ISSUE THREAD

**Issue by sniis84** [Ramotion/folding-cell#17]
I followed the instructions and I achieved the effect I wanted, but I still get this warning that I don't understand how to remove.

`<Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.`

Could you please help?

**Comment by MaxToyberman** [comment]
I am facing the same problem ,The problem is that in the file FoldingCell the problem occurs here :
`    CGContextTranslateCTM(context, frame.origin.x * -1, frame.origin.y * -1)`
in the `extension UIView` ,frame.origin.x and frame.origin.y are 0 .

**Comment by Jauzee** [comment]
Seems like this was a message from Xcode ~8.1-8.2 log outputs.
