### ISSUE TITLE
When cell expands the top goes blank

### ISSUE THREAD

**Issue by chadbrochill317** [Ramotion/folding-cell#175]
Hello, 
I have implemented the folding cell, but when I tap it to expand the top part of it disappears entirely. How can I get it to stay the exact same as it was before tapping it? 

Thanks.

**Comment by 0ber** [comment]
Follow the instruction: https://github.com/Ramotion/folding-cell#usage and look the example https://github.com/Ramotion/folding-cell/tree/master/FoldingCell/FoldingCell-Demo
