### ISSUE TITLE
How to collapse all cells in search results

### ISSUE THREAD

**Issue by paulfries** [Ramotion/folding-cell#176]
This is working great thank you!
I added a search bar, and it properly filters all of the results, but it remembers which cells are opened (based on indexpath) and if I segue an opened cell it fails to pass data.

Is there a way to close (unselect) all cells in searchresults?

**Comment by paulfries** [comment]
the problem is that null is passed to the recipient controller.
To recreate:
1) Expand the first cell in the list (or any cell).
2) perform a search - the cell at whatever indexPath you expanded will also be expanded in the search.
3) click a button in the expanded view to trigger the segue --- Crash.

**Comment by golovin47** [comment]
Hello, @paulfries. It looks like there is an issue in your adapter (recyclerview or listview). Example app in this repo doesn't have any additional features like search or stuff like that. If you need some additional feature, you may fork and customize this lib the way you need.

**Comment by 0ber** [comment]
`FoldingCell` is a lib wich add animation for `UITableViewCell`. It contains the method for setting `unselect` cell state https://github.com/Ramotion/folding-cell/blob/master/FoldingCell/FoldingCell/FoldingCell.swift#L267.

UITableView is not a part of the `FolldingCell` lib. And adding search to UITableView it the separate task.
