### ISSUE TITLE
height fix in folding cell

### ISSUE THREAD

**Issue by Aqil92** [Ramotion/folding-cell#178]
I have included tow view in folding cell unfold view have Readmore Text View when I clicked on read more so my card view height doesn't increase.

**Comment by 0ber** [comment]
Please read https://github.com/Ramotion/folding-cell/blob/master/FoldingCell/FoldingCell/FoldingCell.swift#L267

and look an example:
https://github.com/Ramotion/folding-cell/blob/master/FoldingCell/FoldingCell-Demo/MainTableViewController.swift#L30-L31
