### ISSUE TITLE
"contanerView.height too high"

### ISSUE THREAD

**Issue by knappsimon** [Ramotion/folding-cell#18]
Hey, 

i keep getting this message when running my app. kCloseCellHeight and kOpenCellHeight are greater than the storyboard constraint. Any ideas what could be wrong? 

Thanks a lot

**Comment by ober01** [comment]
When itemCount equal 2 your containerView.heigh must equal 2 * foregroundView.height
When itemCount greater 2  your contanerView.height must bigger when  2 * foregroundView.height

**Comment by knappsimon** [comment]
Thanks. i completely misread the code. The folding cell is awesome. Thanks for creating it

**Comment by eman6576** [comment]
That doesn't work for me. I have a foregroundView with height 110. My item count is 2 so I made my container height be 220 since the item count is 2, 220 = 2 * 110 which meets the first case. But I still get a asset error.
`if itemCount == 2 {
      // decrease containerView height or increase itemCount
      assert(contSize.height - 2 * forgSize.height == 0, "contanerView.height too high")
    }
`
I  don't think what @ober01 said above matches what the assert checks in code.

**Comment by HackShitUp** [comment]
Does anyone know how to resolve this issue?

**Comment by mhtranbn** [comment]
you should comment it : `//    if itemCount == 2 {
//            print(contSize.height - 2 * forgSize.height)
//            // decrease containerView height or increase itemCount
//            assert(contSize.height - 2 * forgSize.height == 0, "contanerView.height too high")
//        }
//        else{
//            // decrease containerView height or increase itemCount
//            assert(contSize.height - 2 * forgSize.height >= itemHeight, "contanerView.height too high")
//        }
//    // decrease containerView height or increase itemCount
//    assert(contSize.height - 2 * forgSize.height >= itemHeight, "contanerView.height too high")`
