### ISSUE TITLE
Multiple Sections

### ISSUE THREAD

**Issue by goalguy10** [Ramotion/folding-cell#180]
I have followed the usage guide and the example and can get everything to work perfectly with only one section/prototype cell. When I add a second section/prototype cell I get a big white space above the expanded cell. What has to happen to add multiple sections/prototype cells?

**Comment by goalguy10** [comment]
Actually what is happening is when I select row 1 in section 1 it is expanding row 1 in section 2 as well. How can I fix this?

**Comment by 0ber** [comment]
I added quick example sections folding cell https://github.com/Ramotion/folding-cell/tree/Sections

You need to control cell height for each cell in sections. look changes: https://github.com/Ramotion/folding-cell/blob/Sections/FoldingCell/FoldingCell-Demo/MainTableViewController.swift#L36
