### ISSUE TITLE
Error while executing tableView.beginUpdates() tableView.endUpdates() in didSelectRowAt Method 

### ISSUE THREAD

**Issue by wilz05** [Ramotion/folding-cell#183]
Getting below  error 

> Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (80) must be equal to the number of rows contained in that section before the update (60), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved 

> out).

Application crashes while executing tableView.beginUpdates() tableView.endUpdates()  lines in 
didSelectRowAt function 
Detailed code has been shared in stackoverflow [https://stackoverflow.com/questions/56771477/error-while-executing-didselectrowat-with-tableview-beginupdates-tableview-end](url)

**Comment by igork-ramotion** [comment]
It may happen if your table view data source is changing number of cell during animation. To handle this case you need to implement your own logic and remove begin & end updates methods from animation block or wait until animation is finished before changing number of cells.
