### ISSUE TITLE
Custom FoldingCell Class not working in storyboards when using Carthage

### ISSUE THREAD

**Issue by naterock101** [Ramotion/folding-cell#184]
I downloaded the folding-cell framework via carthage and can confirm in my code i get no errors. However when i go to set it up via the storyboard I can not find the foldingCell class in the dropdown when setting the cells class. If i write it in the outlets do not appear.

**Comment by igork-ramotion** [comment]
It looks like Xcode problem, Storyboard autocompletion doesn't work well when you try to use some file from other module. But if you will type class name correctly it will work. Or if you want you can subclass `FoldingCell` in your module which contains your storyboard and use subclass instead.
