### ISSUE TITLE
Contents disappear when scrolling

### ISSUE THREAD

**Issue by pjlamber** [Ramotion/folding-cell#185]
I apologize in advance but I did not see this issue in any of the previous issues.

If I tap a cell, expand it then scroll to a point that the expanded cell is out of view then scroll back, all the contents of the cell disappear. In fact, it looks like the container cell is removed. 

This doesn't happen all the time and sometimes if you scroll back a few times, the contents appear.

Update: isUnfolded = false when I scroll back to the expanded cell when tableView (_ tableView: UITableView, cellForRowAt indexPath: IndexPath) is called. 

Update: As a temporary solution, i keep track what cells are expanded and call unfold (without animation) in tableView (_ tableView: UITableView, cellForRowAt indexPath: IndexPath)

**Comment by igork-ramotion** [comment]
Yep, it seems that the problem based on table view dequeuing mechanic.  
This library provides only FoldingCell sources, so it is up to developer handle internal states and configure cell state on reuse
