### ISSUE TITLE
Slow Animation

### ISSUE THREAD

**Issue by smalik02** [Ramotion/folding-cell#186]
Whenever we push a vc and come back to the main tableview containing the folding cells, the animation process is very slow and clunky. 

Running on iOS13, the problem doesn't occur on iOS12. Not using Hero pod (some previous bug experienced it with that pod). 

Any thoughts?

**Comment by igork-ramotion** [comment]
Example doesn't contains any transitions. I've add push transition for test, but do not see any problems. Tested on iPhone 7 iOS 13. 
Please provide sample code how you implement this transition. What device do you use for test? 
Did you check your project with profiler to get more info what exactly is very slow in execution?

**Comment by smalik02** [comment]
I profiled the simulator and my phone (iPhone X) running the build and did not find any memory leaks. 

The implementation is a tableview cell that pushes a new vc. When navigating back, the cell animates very slowly. 

I'll run through the example again to see if I missed anything.
