### ISSUE TITLE
Width compressing

### ISSUE THREAD

**Issue by sekhar9989** [Ramotion/folding-cell#188]
![Simulator Screen Shot - iPhone Xʀ - 2019-10-21 at 00 28 22](https://user-images.githubusercontent.com/52541878/67164611-040d3b80-f39a-11e9-93ee-9204740d9e37.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-10-21 at 00 28 26](https://user-images.githubusercontent.com/52541878/67164612-040d3b80-f39a-11e9-8677-0f726f542f3e.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-10-21 at 00 30 09](https://user-images.githubusercontent.com/52541878/67164613-04a5d200-f39a-11e9-846b-de60563891e3.png)

widths of view which are inside cell are compressing and animations also not visible.
Here am attaching my actual screen's screenshot and after using folding cell pod.

**Comment by igork-ramotion** [comment]
@sekhar9989 hi!) It is too difficult to get any useful information from provided screenshots to understand the reason of your problem. Please take a look at example how to use this library hope it will help.
