### ISSUE TITLE
Rendering (screen width) issue on iPad

### ISSUE THREAD

**Issue by armandr** [Ramotion/folding-cell#196]
Folding cell from the Showroom App gets cropped off and does not unfold properly when viewed on an iPad.

In my case, iPad 7, iPadOS 13.5.1

![IMG_0057](https://user-images.githubusercontent.com/11222953/85564240-16f89f80-b5fc-11ea-8077-9da53b52a7bd.png)

**Comment by igork-ramotion** [comment]
@armandr Hey, I've try to reproduce your case on simulator, but for me both examples (objc & swift) looks as they should.. 

<img width="741" alt="Screenshot 2020-06-29 at 14 36 43" src="https://user-images.githubusercontent.com/53435668/86000575-63861580-ba16-11ea-9e96-a7aff2637be0.png">
<img width="741" alt="Screenshot 2020-06-29 at 14 36 41" src="https://user-images.githubusercontent.com/53435668/86000592-67b23300-ba16-11ea-84e1-831bf0e5d277.png">

You can try to use iPhone for better experience. Or provide more details to reproduce your case
