### ISSUE TITLE
TableView Automatic Dimension in Height for row

### ISSUE THREAD

**Issue by MohanFidtri** [Ramotion/folding-cell#198]
Is it possible to use Automatic Dimension For Cell Heights, Will Folded Animations Work On that particular Scenario?

**Comment by igork-ramotion** [comment]
@MohanFidtri Hey, unfortunately this is not supported. You need to set height manually

**Comment by MohanFidtri** [comment]
> @MohanFidtri Hey, unfortunately this is not supported. You need to set height manually

Is animation is Visible when the height is greater than 1000
