### ISSUE TITLE
Objective-c version

### ISSUE THREAD

**Issue by lhyhsx** [Ramotion/folding-cell#2]
No Objective-c version?

**Comment by ober01** [comment]
only swift

**Comment by mythodeia** [comment]
first of all thanks for open sourcing this great animation
 :+1: i would love to see this in obj-c too

**Comment by BleuGamer** [comment]
I don't think this project belongs with obj-c, with swift becoming a compiled language it's not needed in the slightest but to older projects that are written in obj-c. If someone is willing to re-write or port it to the framework, I'm sure there are some that would be thrilled.

**Comment by afiq90** [comment]
It is possible to use this awesome library in objective-c project ?

**Comment by calvinteoh** [comment]
Is it possible to provide an example of how these swift classes can be used in an objective-c project? I try to do this but had failed to make it work (I am new to swift).

It would greatly benefit a lot of people if someone can provide the right method of how to use this in objective-C through referencing swift classes.

**Comment by Jauzee** [comment]
Sorry for the delay.

I just created Objective-C demo app and you can check it out on `master` branch.

Because of we can not to subclass Swift classes in Objective-C we'll need to obtain our cell's subviews by their tags.
