### ISSUE TITLE
2 Custom tableviewCells in the same TableView

### ISSUE THREAD

**Issue by YoousefAlaa** [Ramotion/folding-cell#200]
I was trying to use this folding animation in my tableview but I couldn't, because this animation works using only one static cell with 2 parts foreground and container.
now I want to use this animation in my tableview which have 2 different tableview cells classes but this doen't fit with your model.
can you please take a look at this?
Thanks in advance

**Comment by igork-ramotion** [comment]
@YoousefAlaa hey!) It can be used with two different cell types, but you need to write additional logic to handle table view data source and delegate methods based on different cell types. Please take a look at the demo code, you can find DemoCell. You can create two cells by taking DemoCell as example. Or even only one cell if second cell shouldn't support folding animation.   
Currently this library support only interface builder customization. Hope in future we will have time to make available it from source code.
