### ISSUE TITLE
Port for android

### ISSUE THREAD

**Issue by nvnguyenit** [Ramotion/folding-cell#22]
Hi man!

Can you estimate port this control for android? and send estimation to nvnguyen.it@gmail.com . thank so much

**Comment by Juriv** [comment]
Hi, we are going to implement it for android but a bit later, our android devs are working on a customer project now

**Comment by nvnguyenit** [comment]
@Juriv thanks man, hope it done soon ^_^

**Comment by Juriv** [comment]
@nvnguyenit done 
https://github.com/ramotion/folding-cell-android
