### ISSUE TITLE
Labels show wrong row while cell is opening

### ISSUE THREAD

**Issue by sniis84** [Ramotion/folding-cell#25]
I have a tableview made of folding cells.
Each cell has a label which shows a row of the indexPath.row of the tableview.
Clicking on the cell the cell "opens" showing the same label of the closed cell and other information related to the same indexPath.row.
While I scroll the tableview everything is perfect.
On the contrary while the cell is opening the labels show the wrong text (they show the text of other rows not the previous or the following, the index is related to a text that is further up or down).
Of course the cell is completely open everything is fine also while I scroll the tableview.

Any idea how to solve this?
Thanks

**Comment by ober01** [comment]
this problem describe in this post http://www.thomashanning.com/the-most-common-mistake-in-using-uitableview/

I hope this helps

**Comment by sniis84** [comment]
I read that post and using that solution I have an empty content when I open the cell because of the `nil`
In order to 'refresh' the content I need to scroll up or down, therefore that does not solve my problem :(

**Comment by ober01** [comment]
#26

**Comment by sniis84** [comment]
#26 does not help much. I think it contains the same question I asked. 
Any more help?

**Comment by ober01** [comment]
Added in example
