### ISSUE TITLE
Customise Height of Different 'Folds'

### ISSUE THREAD

**Issue by GuappaApps** [Ramotion/folding-cell#28]
How would we go about customising the height of each of the folds of the cell animation @Pakhaliuk ? I know I can change the height of each of the views within the 'open' cell but then the animation still loads them at the pre-defined (and seemingly same height for every subview).

Can we edit the animation and if so, how? 
Thanks very much for being awesome and sharing this!

**Comment by ober01** [comment]
You can't customise height of different folds

**Comment by GuappaApps** [comment]
That's a huge shame. Pretty useful thing to be able to do isn't it though? 

What happens when building with larger navigation bars or smaller devices? The cells don't fit on the screen....so to make this library useful, I would say it's pretty important that people like I can customise the folds :(

**Comment by GuappaApps** [comment]
The real answer is that you CAN edit the folds - albeit that they all must be equal.
I changed it from 4 'folds' or items to 3 and therefore will be afforded much more space to separate the content in the cell.

<img width="249" alt="screen shot 2016-03-16 at 10 12 16" src="https://cloud.githubusercontent.com/assets/14874241/13817311/bede565c-eb5f-11e5-9bfa-9bcf76defc9a.png">
