### ISSUE TITLE
Possible No Storyboard?

### ISSUE THREAD

**Issue by syky27** [Ramotion/folding-cell#29]
Hi, this looks really cool!

But I am having trouble to implement this to my app with no storyboard?

Could you please provide me with sample project where is no storyboard?

Huge thanks!

**Comment by ober01** [comment]
1. You can create cell in xib file (1 - 3 steps).
2. After in your UITableViewController in `viewDidload` register your cell 
`self.tableView.registerNib(nib: ,forCellReuseIdentifier: )`
3. Do 4 - 6 steps

**Comment by ober01** [comment]
#20
