### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bianxu** [Ramotion/folding-cell#3]
![d64bf8bb-b82c-4f2b-a5be-11ba5b83b9a5](https://cloud.githubusercontent.com/assets/13793820/12774637/c7960b36-ca81-11e5-8355-db81f75fbe7d.png)

**Comment by ober01** [comment]
This happens when multiple tapping on FoldingCell when is animating ?

**Comment by bianxu** [comment]
Click on the same cell in a row

**Comment by ober01** [comment]
fixed
