### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by SAELH** [Ramotion/folding-cell#30]
Hello First of all i want to thank you on this amazing project.
and second of all i want to ask about an issue that i encounter which is I keep having an error about the range on this code:

    override func tableView(tableView: UITableView, heightForRowAtIndexPath indexPath: NSIndexPath) -> CGFloat {
        return cellHeights[indexPath.row]
    }

I want to know exactly where is the problem and i have another questions if it possible when i downloaded the project to my desktop and examine the design i notice that showing the design as in the image which showing the map is not really in the demo so if how i can apply it on the demo, that is it and thank you again

**Comment by ober01** [comment]
cellHeights.count must be equal numberOfRowsInSection
