### ISSUE TITLE
Bounce Animation

### ISSUE THREAD

**Issue by nanohaddad** [Ramotion/folding-cell#32]
I loved the second animation in the GIF, but don't see any code on implementing it. Has anyone figured out how to implement it? and is there a reason you guys didn't post the code - any issues with the animation itself? 

Thanks for everything
I love the work you guys are sharing with us!

**Comment by nanohaddad** [comment]
Just to clarify, it's the animation that slides up and pushes down a page view controller with a map.

**Comment by nanohaddad** [comment]
Nevermind, I realized how easy this was using the top layout guides, for anyone trying to do this who overlooked how simple this may be, here are the steps for recreating it: 

1.) Set IBOutlets of the following to the "FoldingCell" class: 

- Bottom container view's top layout guide constraint
- Third container view's top layout guide constraint
- Second container view's top layout guide constraint

2. In your Table View class, access the declared cell of type "FoldingCell" 

3. Set the IBOutlet's (that you just created) constant property to whatever you want
(e.g. cell.bottomContainerTopLayout.constant = x)

4. After setting all three constraint constants, animate it the layout

            cell.bottomCellTopLayout.constant = 100
            cell.thirdCellTopLayout.constant = 0
            cell.secondCellTopLayout.constant = 0
            
            UIView.animateWithDuration(0.6) {
                
                self.view.layoutIfNeeded()
            }

5. delay the next set of constants for closing back up equal to however long the opening took. 
            delay(0.6) {
                
                cell.bottomCellTopLayout.constant = 402
                cell.thirdCellTopLayout.constant = 330
                cell.secondCellTopLayout.constant = 165
                
                UIView.animateWithDuration(0.6) {
                    
                    self.view.layoutIfNeeded()
                }
            }

6. Adjust the above numbers to fit whatever you want, **the above method is kinda janky with those numbers** , to replicate their bounce up you need to delay each constraint layout to start right as it's respective bottom one hits it.

If anyone sees a better way / issues with my code please feel free to let me know!! 
Thank you

**Comment by Jackson0111** [comment]
Hey! @nanohaddad nice tricks! I tried it your way, everything works great except the cell itself doesn't scroll up like the animation in the gif (It looks like the height of the cell is changed because when the animation starts, the following cells actually scroll up with it). Any ideas?

**Comment by Stan92** [comment]
Thanks for the tricks.. I ll try your code asap...
Just a question, don't you think (except if I didn't understand your explanations)  the map is inside a container with of height of Zero at start?
I mean using your example, there would be 
FirstContainerView
MapContainerView  <- New one
SecondContainerView
ThirdContainerView
BottomContainerView

**Comment by jsdu** [comment]
Hi, do you have an example project of this?

**Comment by ober01** [comment]
Folding-cell supports only folding animation
