### ISSUE TITLE
Foreground and Container constraints

### ISSUE THREAD

**Issue by matheusleite** [Ramotion/folding-cell#33]
My foreground and container constraints are nil. 
I follow the instructions on tutoriaI and I don't know the reason

Check the screenshots
![screen shot 2016-05-12 at 12 12 59](https://cloud.githubusercontent.com/assets/7133438/15219761/5797c510-183b-11e6-8f1d-918d8e51cf13.png)
![screen shot 2016-05-12 at 12 13 37](https://cloud.githubusercontent.com/assets/7133438/15219762/579cae5e-183b-11e6-9a36-1b7e209bbbd7.png)
![screen shot 2016-05-12 at 12 13 46](https://cloud.githubusercontent.com/assets/7133438/15219763/579fc27e-183b-11e6-94ec-a1f5272b122e.png)
![screen shot 2016-05-12 at 12 14 06](https://cloud.githubusercontent.com/assets/7133438/15219764/57a5de34-183b-11e6-890b-a99c167157b6.png)

Thanks for helping

**Comment by ober01** [comment]
**Add the identifier "ForegroundViewTop" for the top constraint**. (step 2 and 3)

**Comment by matheusleite** [comment]
I already set the identifiers. The screenshots it's how the my code is. It's not a tutorial

**Comment by Sudhir007** [comment]
Same thing is happening for me, While I have also added the Constraints to **"ForegroundViewTop"**

**Comment by arifmc** [comment]
Happened to me too, already add the identifier to the top constraints

**Comment by seyhunak** [comment]
same here.

**Comment by ober01** [comment]
Added constraint outlests instead  constraint identifiers
