### ISSUE TITLE
Rounded Edges

### ISSUE THREAD

**Issue by jmp9c** [Ramotion/folding-cell#34]
So, I was able to get the top corners rounded (following the project you uploaded). Any reason why it is cutting off the bottom rounded corners?
![messages image 2857556704](https://cloud.githubusercontent.com/assets/12173944/15447241/8534e102-1f01-11e6-8ade-76105e0dd1d4.png)

**Comment by jmp9c** [comment]
To fix this: Make your kCloseCellHeight and kOpenCellHeight values bigger

**Comment by theraad** [comment]
Do you mean just the constants? or the views in the interface builder as well?

**Comment by jmp9c** [comment]
this was over a year ago and we decided to not use this feature, so I don't really remember..... but I think these values were in code somewhere. and I think they are constraints as well.
