### ISSUE TITLE
Crash regrading container height

### ISSUE THREAD

**Issue by karnakar** [Ramotion/folding-cell#37]
My foreground view height  is 170, container count = 2, so i made my container height = 340 but it is still crashing. I tried different heights between 300 to 400. I followed as per the formula 

When itemCount equal 2 your containerView.heigh must equal 2 \* foregroundView.height
When itemCount greater 2 your contanerView.height must bigger when 2 \* foregroundView.height
Solution plz?

**Comment by Sidrock28** [comment]
Play with the duration is "didSelectRowAtIndexPath".  My example:
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        // Expands cell by unfolding if cell is folded and vice-versa
        let cell = tableView.cellForRowAtIndexPath(indexPath) as! SpotTableViewCell
        
        let forRowSpotInfo = self.spotList[indexPath.row]
        
        var duration = 0.0
        if cellHeights[indexPath.row] == closeCellHeight { // open cell
            
            cellHeights[indexPath.row] = openCellHeight
            if let locationData = self.userLocation {
                
                cell.unfoldedCellInfo(forRowSpotInfo, userLocationData: locationData) // Unfolded Cell Info
                
            }
            cell.selectedAnimation(true, animated: true, completion: nil)
            **duration = 0.25**
            cell.configureContainerView(true) // ContainerView Shadow
            
        } else {// close cell
            
            cellHeights[indexPath.row] = closeCellHeight
            cell.selectedAnimation(false, animated: true, completion: nil)
            **duration = 0.55**
            
            cell.setDefaultLabelTitleForWeatherAndTimeButton()
            
            // Delaying shadow clearing process using GCD
            let seconds = 0.25
            let delay = seconds * Double(NSEC_PER_SEC)  // nanoseconds per seconds
            let dispatchTime = dispatch_time(DISPATCH_TIME_NOW, Int64(delay))
            
            dispatch_after(dispatchTime, dispatch_get_main_queue(), {
                
                cell.configureContainerView(false)
                
            })
            
        }

**Comment by eman6576** [comment]
I am having a similar issue where my container height is 378 and I have the itemCount is 1. Any solution?

**Comment by eman6576** [comment]
Also @Sidrock28 how does the animation duration solve this?

**Comment by ahegazi18** [comment]
this didn't solve the issue

**Comment by ober01** [comment]
Need to set height constraint to 340 
<img width="1160" alt="image 2018-03-27 at 12 19 22 pm" src="https://user-images.githubusercontent.com/5435782/37958509-62ed441e-31b9-11e8-9d2c-15659bcc1f35.png">
