### ISSUE TITLE
Specify background cover of fold

### ISSUE THREAD

**Issue by tiferrei** [Ramotion/folding-cell#39]
I have a slight issue with this framework, my "cards" are all with white background but when folding or unfolding the background of the other face of the card is a wired brown! How did this happen? I mean I didn't even specific any colour! Here are some screenshots to help clarify. 

I also have a bit of a problem with some constrains, it gives me the "`Unable to simultaneously satisfy constraints`" look, it also seems to happen in each "card":

```swift
2016-06-06 23:05:45.912 GL Dash[542:87484] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x127678ec0 V:[UIView:0x1276654c0(350)]>",
    "<NSLayoutConstraint:0x1276beef0 V:[UIView:0x1276654c0(132)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x127678ec0 V:[UIView:0x1276654c0(350)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-06-06 23:05:45.914 GL Dash[542:87484] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 

		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1276beef0 V:[UIView:0x1276654c0(132)]>",
    "<NSLayoutConstraint:0x1276c2010 V:[UIView:0x1276654c0(75)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1276beef0 V:[UIView:0x1276654c0(132)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

Tiago

![img_3299](https://cloud.githubusercontent.com/assets/8849915/15839338/bc0bc718-2c3a-11e6-81eb-aea1f3af8b07.PNG)
![img_3300](https://cloud.githubusercontent.com/assets/8849915/15839339/bc4f7314-2c3a-11e6-94c5-58b181846ed3.PNG)
![img_3301](https://cloud.githubusercontent.com/assets/8849915/15839340/bc57ba06-2c3a-11e6-9a8e-1f373f817d9f.PNG)
![img_3302](https://cloud.githubusercontent.com/assets/8849915/15839341/bc58e1c4-2c3a-11e6-9130-3b5b7d7841b6.PNG)

**Comment by Sidrock28** [comment]
![screen shot 2016-06-11 at 4 07 29 pm](https://cloud.githubusercontent.com/assets/6657673/15987219/f97ca42a-2fee-11e6-9383-a7e427c92b95.png)

**Comment by jdulb17** [comment]
Hi tiferrie, did you have to do any additional tweaking to the code to make your unfolding animation line up properly with the views?

**Comment by tiferrei** [comment]
Sorry @jdulb17, I ended up not using this framework, was using a loads of RAM and the animations sometimes messed up the content.
