### ISSUE TITLE
Xamarin and Folding Cell

### ISSUE THREAD

**Issue by makerofthings7** [Ramotion/folding-cell#44]
I'm having issues with connecting this lib (and others) to Xamarin. Perhaps you can lend some expertise: 

http://stackoverflow.com/q/37912369/328397

**Comment by Jauzee** [comment]
@makerofthings7 sorry for the delay. There are some _hacky_ way to make it work with `Xamarin` as it was noted in the answer on SOF. There is nothing to do on our side I think.
