### ISSUE TITLE
Swift 3 and Xcode 8

### ISSUE THREAD

**Issue by jmp9c** [Ramotion/folding-cell#47]
When I updated to Swift 3 and Xcode 8, it seemed to break the small views. When the cell is opened, everything looks fine, but when closed the cells are only showing the bottom halves. 
![img_2466](https://cloud.githubusercontent.com/assets/12173944/16533802/f1ef3fc6-3fa0-11e6-94d4-7c965be8d440.PNG)
![img_2467](https://cloud.githubusercontent.com/assets/12173944/16533803/f208f182-3fa0-11e6-920a-2f312040973f.PNG)

**Comment by FlorianPfisterer** [comment]
Any fix yet?

**Comment by croossin** [comment]
Is there any timeline as to when you think there might be Swift 3 support? Thanks!
