### ISSUE TITLE
Alternative way of installation

### ISSUE THREAD

**Issue by sebastianbachmann** [Ramotion/folding-cell#48]
Hi Ramotion-Team,

you've written in the docs, right below the _Installation[1]_ headline: `Just add the FoldingCell.swift file to your project.` In other words, i can clone the project and drag and drop the `FoldingCell.swift` file manually, and do not have to use CocoaPods or Carthage?!

[1] https://github.com/Ramotion/folding-cell#installation

**Comment by jmp9c** [comment]
You should be able to do that. You can also just make a new swift file and just copy and paste the code in there and name the file FoldingCell.swift
