### ISSUE TITLE
Dramatically slow

### ISSUE THREAD

**Issue by Luccifer** [Ramotion/folding-cell#50]
Hello! Any ideas to use multi-threading or etc to faster the set-up/init time? The set-up time grows from 6s(iphone 6s) to 30/40s (iphone 5c/4s)! 
What can be a problem? How to solve the time spreading? 
Anyway tnx for response!

**Comment by jitz2010** [comment]
Yes true, while adding show storyboard segue.......

**Comment by Luccifer** [comment]
I calculated execution time and achieve following results: 
Tests were made in simulator even with power of Intel Processor MBP mid 2012 and the most long-execution functions are:
transform3d() Time: 6.02006912231445e-06
tableView(_:willDisplayCell:forRowAtIndexPath:) Time: FROM 1.69873237609863e-05  TO 9.80496406555176e-05

Can the execution time be so much longer if we use different fonts and other font-work in SB when configuring the folding cells? Anybody tested? Cause I heard from colleagues that thing is eating performance a lot...

**Comment by Satchitananda** [comment]
@Luccifer I've gone deeper in profiling and found out that such slow behavior related with not existing font loading. I changed all fonts to system and now it takes only one second to init.

**Comment by Luccifer** [comment]
@Satchitananda, thanks a lot! I love check this today's evening, if it's so, you will be my hero :D

**Comment by Luccifer** [comment]
Yep! It's worked! Now is quite fast!
