### ISSUE TITLE
Best Way To Increase Size Of foregroundView Without Hurting the UI

### ISSUE THREAD

**Issue by JudeMurphy** [Ramotion/folding-cell#52]
I need to make the foregroundView larger to fit an image. I want them all to be the same height. I have been trying to figure this out for days now, and can't seem to get it right. Does anyone have sample code?

**Comment by ober01** [comment]
Use Constraint to change the height of ForegroundView
![screen recording 2018-03-27 at 12 50 pm](https://user-images.githubusercontent.com/5435782/37960169-96f1e996-31bd-11e8-9bfb-c8014cbcd028.gif)
