### ISSUE TITLE
Unfolding Animation Slightly Off

### ISSUE THREAD

**Issue by jdulb17** [Ramotion/folding-cell#53]
When I open or close the cell, I noticed that the unfolding animation is slightly to the left of where it should be. Is there a way to fix this?

**Comment by robin43499** [comment]
idk that my solution will surely help you.

I had set base value to be Compact : any, then i found problems like u.

So, I have set base value to be any : any. And then the animation works well where it should be.

**Comment by jdulb17** [comment]
Thanks for the idea, @robin43499 ! I gave it a try, but sadly, it did not fix the issue. May I ask what your constraints are for the views, please?

**Comment by robin43499** [comment]
@jdulb17 I use the constraints as same as the Demo.

I fixed it by doing it in a new storyboard.

https://github.com/Ramotion/folding-cell/tree/master/FoldingCell/FoldingCell

**Comment by Jauzee** [comment]
Sorry for the delay guys. I'll close this issue because it seems like it was fixed by latest updates.
