### ISSUE TITLE
Where to add "animationDuration" method?

### ISSUE THREAD

**Issue by joaoh82** [Ramotion/folding-cell#54]
I created everything with the storyboard, justing setting the cell to FoldingCell, where do I add this method?

`override func animationDuration(itemIndex:NSInteger, type:AnimationType)-> NSTimeInterval {

        // durations count equal it itemCount
        let durations = [0.33, 0.26, 0.26] // timing animation for each view
        return durations[itemIndex]
    }`

**Comment by jdulb17** [comment]
I had the same issue. What you have to do is create a new class that inherits from FoldingCell, like so:  `class CustomCell: FoldingCell`, and paste it in there. Then, make your table cell (not the views inside it) inherit your custom cell
