### ISSUE TITLE
Height of Container View is shorten

### ISSUE THREAD

**Issue by panditbhavi** [Ramotion/folding-cell#55]
Awesome work, I am using your code and it helpful for my requirement, but I have two issue like 
-  I have description label in containerView in which I have to show the only 3 line with more button, when I click on that more button and increase the height or I set UITableViewAutomaticDimension then it shrink height.  
- In containerView, I have Like button as I hit the like button, I am scrolling the tableview then click on fold button then that cell is freeze not click or user interaction working on that cell 

Please guid me where is my mistake

Thanks  :)

**Comment by BlackDeveraux** [comment]
@panditbhavi Can you please share some of your code?

**Comment by panditbhavi** [comment]
Hello,
  Her you go the code of the more and less text.

   ```
![after_click_on_more](https://cloud.githubusercontent.com/assets/1292120/19338389/50fc43ca-913a-11e6-8122-5bea81629baa.png)
![simple](https://cloud.githubusercontent.com/assets/1292120/19338390/50ffc6da-913a-11e6-94c2-671b7009ca19.png)


 func more(sender: UIButton){
        
        let indexPath: NSIndexPath = NSIndexPath(forRow: sender.tag, inSection: 0)
        
        let cell = tableView.cellForRowAtIndexPath(indexPath) as! FoldingCell
        if cell.isAnimating() {
            return
        }
        
        var duration = 0.0
        
        cellHeights[indexPath.row] = UITableViewAutomaticDimension
        cell.selectedAnimation(true, animated: true, completion: nil)
        duration = 0.5
        
        UIView.animateWithDuration(duration, delay: 0, options: .CurveEaseOut, animations: { () -> Void in
            self.tableView.beginUpdates()
            self.tableView.endUpdates()
            }, completion: nil)

    }
```
![after_click_on_more](https://cloud.githubusercontent.com/assets/1292120/19338435/a8799210-913a-11e6-89b1-45a75e669b76.png)
![simple](https://cloud.githubusercontent.com/assets/1292120/19338436/a87d20a6-913a-11e6-8738-1f5eb6140d89.png)

Please suggest

**Comment by ober01** [comment]
1. Create a new cell inheriting from FoldingCell
![1 create democell](https://user-images.githubusercontent.com/5435782/38353931-a68da34a-38c0-11e8-8eb2-d0909fd3698b.gif)

2. Add a UIView to your cell in your storyboard or nib file, inheriting from RotatedView. Connect the outlet from this view to the cell property foregroundView
![3 create foreground view](https://user-images.githubusercontent.com/5435782/38354072-f741e918-38c0-11e8-9223-340639586ac6.gif)


3. Add other UIViews to your cell, connect the outlet from this view to the cell property containerView
![2 create container view](https://user-images.githubusercontent.com/5435782/38353985-c797559a-38c0-11e8-8d7b-3f36505e10c7.gif)

4. Set @IBInspectable var itemCount: 
![4 set item count](https://user-images.githubusercontent.com/5435782/38354139-2b720b0a-38c1-11e8-80c2-e3c9ddb8e672.gif)

continue step 5 https://github.com/Ramotion/folding-cell/blob/master/README.mdl
