### ISSUE TITLE
Does FoldingCell work with reordering and deleting cells?

### ISSUE THREAD

**Issue by Reservations** [Ramotion/folding-cell#57]
I have a task list app that I want to implement folding cells into, but I want to make sure that cell folding behavior will still be as expected after deleting and reordering cells in the table view.

**Comment by Jauzee** [comment]
@Reservations sorry for the delay. Developers was so busy and they missed a lot of issues here.

Reordering table view cells is supported by default. Additionally to standard reordering you'll need to reorder values in `cellHeights` array accordingly to your changes.

I think there is no issue for you anymore, but maybe somebody find this helpful.
