### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by gorbat-o** [Ramotion/folding-cell#58]
Hey, 

is it normal that when i launch my tableview with folding-cell it's takin' 3 seconds maybe 4 for launch? :/

Sad :(
Thanks

**Comment by dev-vinoth** [comment]
I have the same issue

**Comment by mradzinski** [comment]
Has any of you tried the #50 approach of changing everything to use system fonts?

**Comment by dev-vinoth** [comment]
Yea issue is fixed by using system fonts.
