### ISSUE TITLE
anchorPoint modifications in FoldingCell.swift causes shifts in subviews of foregroundView

### ISSUE THREAD

**Issue by BlackDeveraux** [Ramotion/folding-cell#59]
Hello!

I recently got this library up and running in my project, and I just want to start by thanking @Ramotion for creating this library. It's amazing!

This is a mockup I've drawn in sketch delineating what I'd like to accomplish:
![screen shot 2016-08-15 at 7 47 11 pm](https://cloud.githubusercontent.com/assets/7029790/17663967/36f9adb8-6323-11e6-9cf2-ed1685cc7e94.png)

The issue I have at hand is that the default library appears to be defining an anchorPoint (shown below) that puts my content in the wrong position. 

`foregroundView.layer.anchorPoint = CGPoint.init(x: 0.5, y: 1)`

Here's a visual showing the green UIView covered by the NavigationBar:
<img width="299" alt="screen shot 2016-08-15 at 7 43 58 pm" src="https://cloud.githubusercontent.com/assets/7029790/17663648/a418f802-6320-11e6-86fb-42d4316f02d0.png">

If I remove the line of code shown above, I get it to work (partially).
The other problem is that the foregroundView exceeds my defined height.
<img width="295" alt="screen shot 2016-08-15 at 7 45 49 pm" src="https://cloud.githubusercontent.com/assets/7029790/17663983/5c76ab22-6323-11e6-8da7-fe99bb9e105b.png">

To give some more context, I've set the cell heights programmatically in my primary TableViewController as 120 pixels:

`var itemHeight = [CGFloat](count: 1, repeatedValue: 120.0)`

I define the layout constraints of my foreground/container views in TestCell.swift which inherits from FoldingCell.swift, the code below is supposed to set the foregroundView height at 110 pixels.
<img width="798" alt="screen shot 2016-08-15 at 8 06 20 pm" src="https://cloud.githubusercontent.com/assets/7029790/17664047/c2d54900-6323-11e6-972b-bf73eab1a10f.png">

How might I be able to resolve this issue?
Any help is appreciated!

**Comment by ober01** [comment]
You set wrong cell height (in example kCloseCellHeight), it must be equal:

CellHeight = foregroundViewHeight + foregroundViewTopConstraint.constant * **2**

**Comment by BlackDeveraux** [comment]
@ober01 Hi Alex!

So the TableViewCell Height should be 130?

Cell Height = fgHeight (110) + topConstraint.constant (10) * 2

**Comment by ober01** [comment]
yes, or top constraint must be 5

**Comment by BlackDeveraux** [comment]
@ober01 

This is what happens when I set the cellHeight = 120, fgHeight = 110 and topConstant = 5
<img width="301" alt="screen shot 2016-08-16 at 3 39 39 pm" src="https://cloud.githubusercontent.com/assets/7029790/17691572/d8bd934a-63c7-11e6-8a0e-f6c0f102eb12.png">

**Comment by ober01** [comment]
can you share this example ?

**Comment by BlackDeveraux** [comment]
Absolutely!

Here is a link to the entire project, hosted on Mega.nz if you don't mind :)
https://mega.nz/#!AJERSbQD!U9rGx1-taAk11jcdpIC_D3y2Es-UpdZv2DGjecYil-A

**Comment by robin43499** [comment]
Hi, idk that the problem is what you set at base value.

I had set base value to be Compact : any, then i found problems like u.

So, I have set base value to be any : any. And then the animation works well where it should be.
