### ISSUE TITLE
Feature: React native wrapper

### ISSUE THREAD

**Issue by ahmed1490** [Ramotion/folding-cell#6]
This is an awesome pod.
I am so sure, developers working with react native will love it.

example way to have a bridge for react native: https://facebook.github.io/react-native/docs/native-modules-ios.html#content

**Comment by dev-vinoth** [comment]
Do you any example with this folding cell in react native?@ahmed1490

**Comment by Jauzee** [comment]
We do not plan to support react native yet. Feel free to contribute!
