### ISSUE TITLE
Getting run time error

### ISSUE THREAD

**Issue by kanishkatn** [Ramotion/folding-cell#60]
Hi,

I am getting the following run time error while trying to run the app. 

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Must translate autoresizing mask into constraints to have _setHostsLayoutEngine:YES.'

Please help me

Figured it somehow. I am getting this error now

![screen shot 2016-08-23 at 8 07 48 pm](https://cloud.githubusercontent.com/assets/4919645/17896210/5ca7ebb0-696d-11e6-84cd-b04016bbbf20.png)
![screen shot 2016-08-23 at 8 08 01 pm](https://cloud.githubusercontent.com/assets/4919645/17896218/66da42b8-696d-11e6-959c-9c82c7cd35de.png)

**Comment by jotayc** [comment]
Override awakeFromNib() and assign the outlets there

**Comment by kanishkatn** [comment]
Done. Thanks :)

**Comment by Arcrammer** [comment]
Would you guys consider putting this in the README.md? I was stuck at step 3 and wouldn't have figured it out without this issue. Make it n00b friendly!
