### ISSUE TITLE
createAnimationItemView() Fatal error 

### ISSUE THREAD

**Issue by jotayc** [Ramotion/folding-cell#62]
I don't know why I get the next error.

<img width="695" alt="captura de pantalla 2016-09-02 a las 14 51 17" src="https://cloud.githubusercontent.com/assets/7070284/18204413/f79b8efe-711c-11e6-8c38-3b672bf13abc.png">

does someone knows why?

Thanks

**Comment by LukasHaas** [comment]
I am getting exactly the same error!

**Comment by Tomm89** [comment]
Has somebody some solution? I am getting the same error.
