### ISSUE TITLE
ETA for Swift 3.0 or 2.3 support?

### ISSUE THREAD

**Issue by Sidrock28** [Ramotion/folding-cell#65]

**Comment by kunwarh** [comment]
Yep new Xcode 8 needs swift 3.0 version. ETA would be really helpful.

**Comment by emonfil87** [comment]
not compatibility with swift 3

**Comment by XOneto9** [comment]
It make me crazy to not compatiblity new version of swift3 T^T

**Comment by nevinjethmalani** [comment]
Would love an ETA on this. Really appreciate the help.

**Comment by Brdjx** [comment]
I am with everyone here. I'd love to have an ETA on the update to Swift 3

**Comment by stephangopaul** [comment]
If you need swift2.3 compatibility, you can have a look at [my fork](https://github.com/stephangopaul/folding-cell).

**Comment by Lengo46** [comment]
Agree with above

**Comment by stephangopaul** [comment]
If you need swift3 compatibility, [you can have a look at my fork](https://github.com/stephangopaul/folding-cell).
It is in the swift3 branch.

**Comment by Brdjx** [comment]
@stephangopaul I'm not sure if you're having this issue, but when I open the Main.storyboard file before launching the application from your fork, the folding cell's are hidden.

**Comment by stephangopaul** [comment]
@Brdjx Yeah I did get that issue, but you can thank Xcode8 for that. You can try saving the storyboard for xcode 7.x. This worked on my end. [You can check out this link if you need help to save your storyboard to xcode 7.x](http://stackoverflow.com/a/37851922)

**Comment by Brdjx** [comment]
@stephangopaul Thank you very much. I'll look into that for my projects. If I find any solution in the meantime I'll get it.

**Comment by Lengo46** [comment]
@stephangopaul, using your fork doesn't display my folding cells. This also is the case when I alter the Master branch by myself. I tried the xcode 7.x. fix, doesn't work, any ideas what might be the problem?

**Comment by stephangopaul** [comment]
@Lengo46 Each time you open your storyboard, you have to save it using the xcode 7.x. Please note that I noticed that issue regardless if the storyboard contained the folding cell library or not. Definitely an issue with xcode8. Best of luck!

**Comment by aghanimQFI** [comment]
The Xcode 7.x trick worked for me! Thanks, Stephangopaul 👍  :) One question though, would this work when I submit my app to the App Store?

**Comment by Lengo46** [comment]
@stephangopaul 

I did needed to change:

`let context = UIGraphicsGetCurrentContext()`
`context!.translateBy(x: frame.origin.x * -1, y: frame.origin.y * -1)` 

to

` if let context = UIGraphicsGetCurrentContext() {`
`      context.translateBy(x: frame.origin.x * -1, y: frame.origin.y * -1)`
`    }`

or else it crashes in my App. Thanks for the fork!

**Comment by Brdjx** [comment]
Does anyone have any idea what we can do to continue using this framework without reverting the Storyboard to Xcode 7.x?

**Comment by nevinjethmalani** [comment]
What is the downside of  reverting the Storyboard to Xcode 7.x?
