### ISSUE TITLE
still Error with swift3.

### ISSUE THREAD

**Issue by XOneto9** [Ramotion/folding-cell#67]
I'm update foldingcell ver. 2.0.0. using a cocoapods but, still having a error and xcode said that you must change syntax.

This part I don't understand that if I use foldingcell ver. 2.0.0 adopted swift3 syntax, The Xocde dosen't say like this changing syntax of swift3 on folding cell?

**Comment by ober01** [comment]
could you check 2.0.1 version ?

**Comment by Relax594** [comment]
Same for me. 2.0.1 version

**Comment by kunalverma25** [comment]
just click convert..
and save changes and build your project..!!
it happens with almost 80% pods for me.
it will not change anything..
but it still shows this for me.

convert and save.. then build the project again.!
