### ISSUE TITLE
Cells not appearing 

### ISSUE THREAD

**Issue by nevinjethmalani** [Ramotion/folding-cell#68]
There was a discussing about the cells not appearing on another thread regarding swift 3 (linked below). I wanted to post it as another issue so in the future other developers have a solution. 

If anybody knows the downsides of saving the storyboard for xcode 7.x, I would love to understand those so we aren't impacted by them in the future. 

I also wanted to check if this would have any impact on submission to the app store or the use of new features in xcode 8. 

If anybody else has any solutions that do not require us to save the storyboard for 7.x, please let us know!

Has anybody opened a radar for this issue?

https://github.com/Ramotion/folding-cell/issues/65

**Comment by emilyvon** [comment]
I really need a solution to this issue too :(

**Comment by Brdjx** [comment]
I'm having the same issue. My downside for downgrading is that it makes it inefficient to develop an application with having to constantly convert between 7.x and 8.

**Comment by EvansPie** [comment]
A temporary solution (as suggested somewhere else), is to hard-code ```foregroundViewTop.constant``` in ```configureDefaultState()``` equal to half the foreground view's height. It worked for me.

**Comment by Brdjx** [comment]
@EvansPie Thanks for the input. I'm unable to try that solution, but why do you say it is a temporary solution?

**Comment by EvansPie** [comment]
Because you'll have to change it manually every time you update your pod (assuming you are using pods) or every time you want to change the height of the foreground view.

**Comment by boardmain** [comment]
thank you @EvansPie  i added foregroundViewTop.constant value in the awakefromNib and it worked  whitout need to unlock the foldingcell lib ( i only need to remove it when the bug will be fixed)

**Comment by firozkhan09** [comment]
ye not solved. Facing same issue

**Comment by nevinjethmalani** [comment]
That solution worked for us as well. Thanks a lot @EvansPie for helping with that fix. Really appreciate it. 

We put this line of code in 

`foregroundViewTop.constant = 105`

right below 

`foregroundView.layer.transform = foregroundView.transform3d()`

in the `configureDefaultState()` function of the FoldingCell.swift file. 

The 105 for us is the height of the foreground view (see the GitHub page for a reference to which part of the cell that is). It is a constant value that was set in our storyboard so we just plugged it into the code.
