### ISSUE TITLE
sudden crash, table disappear and auto layout constrains issue 

### ISSUE THREAD

**Issue by jams032** [Ramotion/folding-cell#69]
When i change anything like connect new iboutlet or create new connection with existing uilabel, it becomes blank screen. And i dont get anything. I am trying to remove auto layout but can't. 

1. I see the screenshot whe try to connect uilabel and set value for the label. 
![simulator screen shot sep 29 2016 9 42 57 pm](https://cloud.githubusercontent.com/assets/13532330/18961255/33f4029c-868e-11e6-977a-956cd72e43db.png)

2. When i stop autolayout, it crash. Does anything to change in source file or storyboard. 

fatal error: set constratins outlets: file /Users/TOS_Corei5_1/Downloads/folding-cell-2.0.0/FoldingCell/FoldingCell/FoldingCell/FoldingCell.swift, line 92

**Comment by ober01** [comment]
fixed in version 2.0.1

**Comment by jams032** [comment]
Thanks.
