### ISSUE TITLE
Swift3 compatibility with Cocoapods

### ISSUE THREAD

**Issue by joaoh82** [Ramotion/folding-cell#70]
I am trying to get folding-cell 2.0.0 install with cocoapods but I can't. And 1.0.0 it is not compatible with swift3.

What should I do?

Thanks!

**Comment by joaoh82** [comment]
Anyone?!

**Comment by somogyibence** [comment]
Have you tried specifying the version?
```
pod 'FoldingCell', '>=2.0.0'
```

**Comment by joaoh82** [comment]
My mistake... All I had to do is to update the cocoapods to 1.1.0
