### ISSUE TITLE
Problem with xcode 3, cells hidden

### ISSUE THREAD

**Issue by boardmain** [Ramotion/folding-cell#72]
Hi i upgraded the app to swift 3
but when i try a table that use folding cell i have this error:

https://youtu.be/fx_tL4XxWf4

first rows are "hidden" (but visible in the bottom)

you can see in the video what happens

**Comment by boardmain** [comment]
i tried with an empty tableViewController and new foldingcell, but same problem

**Comment by nevinjethmalani** [comment]
We have the exact same issue. See this thread: https://github.com/Ramotion/folding-cell/issues/68
