### ISSUE TITLE
"Request" button action code is missing.

### ISSUE THREAD

**Issue by bhakunineeraj** [Ramotion/folding-cell#73]
Hi, 

As per this demo link "https://dribbble.com/shots/2121350-Delivery-Card", Once the folding card is in open state. The "Request" button action source code is missing.

Could you please provide the Demo Code for that "Request" button and folding cell animation for moving down the cell content and display MAP for direction. 

I need to implement that functionality. Please provide the remaining source code for "Request" button action.

**Comment by ober01** [comment]
Folding-cell project support only folding animation
