### ISSUE TITLE
Assert thrown because containerView too high.

### ISSUE THREAD

**Issue by eman6576** [Ramotion/folding-cell#75]
Hi,

When having the container view with a height of 378, an assert is thrown. Any reason for this?

**Comment by eman6576** [comment]
I also have one item in the container view.

**Comment by ryandailey100** [comment]
Having the same problem too.

**Comment by dgkatz** [comment]
same problem

**Comment by KumaresanSubramaniam** [comment]
directly set assert value like,
assert(true, "contanerView.height too high")

**Comment by ItsMeMIHIR** [comment]
@KumaresanSubramaniam  that is not Proper solution

**Comment by tangjienan** [comment]
the assertion throws when containerView's height is not 2 times the height of the foreground view.

So i change the heights and it works..

hope it helps
