### ISSUE TITLE
Can't install pod for swift 2.2

### ISSUE THREAD

**Issue by OnetreeMobile** [Ramotion/folding-cell#76]
I tried to install version 1.0.0 for swift 2.2 using cocoapods and I get an error
[!] Unable to find a specification for `FoldingCell~> 1.0.0`

How can I solve this issue?

Regards,
Martin

**Comment by dacrystal** [comment]
Try to update your master spec repo:
```
$ pod repo update master 
```

Or if you run into an issue with updating, try to remove it and re-download it (~100MB Ziped):
```
$ pod repo remove master && pod setup
```

PS: Cocoapod/Specs GitHub repo have a rate limit implemented, so be patient.
