### ISSUE TITLE
Is there an example project?

### ISSUE THREAD

**Issue by ryandailey100** [Ramotion/folding-cell#77]
I cant seem to figure out how to use this. Instructions are pretty confusing. Is there an example project that i can download to help aid me?

**Comment by cpvbruno** [comment]
I Agree with @ryandailey100, It would be nice to have a better documentation or a simple example project, Im facing hard times trying to understand the actual doc

**Comment by WrathChaos** [comment]
Completely agree.. They really re-write the usage document and upload an example project.. Could not use this awesome library..

**Comment by JesusAdolfo** [comment]
Seems like a no brainer... I've been struggling to make it work. No luck yet...

**Comment by alperdemirci** [comment]
For swift3, I pod installed the https://github.com/stephangopaul/folding-cell/tree/swift3 branch but seemed like it didn't work. So I ended up copying the FolderCell.swift file to the project directory as well. it works fine for now and I will keep the pod file for future references. 
![screen shot 2017-05-18 at 11 59 31 am](https://cloud.githubusercontent.com/assets/5566064/26211924/cc425f4c-3bc1-11e7-8f91-92a0508d743e.png)

There is also a FoldingCell directory within the project where a demo can be found.

**Comment by JorgeAGomez** [comment]
In the GIF video that shows how this framework works, they have a nice animation that shows a map when they click "Request". Does anyone know if there is a example project for this part?

**Comment by Jauzee** [comment]
Please, checkout `master` branch. Now there are demo apps for Swift & Objc.

**Comment by JorgeAGomez** [comment]
@Jauzee  thanks for the reply. I downloaded the master branch but the map functionality that shows the GIF after tapping " Request " is not there. I am wondering if there is any tutorial or code that shows how to implement that part? 

Thanks in advance.

**Comment by Jauzee** [comment]
@JorgeAGomez this was reply about demo project. There are an issue with your question (#32) and it seems like this functionality was not implemented yet. Please track that issue for any updates & contributions. I'll close this one.
