### ISSUE TITLE
Section headers come missing sometimes during animations

### ISSUE THREAD

**Issue by rjcristy** [Ramotion/folding-cell#82]

**Comment by PrakashMaharjan** [comment]
I also faced this issue, when animated, the sometimes section header is gone and blank space is there.. 
Anybody found the fix for this weird issue?

**Comment by manikad24** [comment]
@PrakashMaharjan please check whether your header is subclass of UIView or UITableViewCell.
if you are using UITableViewCell subclass header it will hide.
Please use UIView Subclass for headers.
