### ISSUE TITLE
[UITabBarController] A bit of a lag

### ISSUE THREAD

**Issue by SirSamShaw** [Ramotion/folding-cell#86]
Hey! I am loving this! Such an amazing feature and animation! I am using it for my table within a tab bar controller. One thing I am noticing is a small lag whenever I navigate to the tab. For instance when I press the corresponding tab, I have to wait about 3 seconds before my hardcoded data appears. Am I doing something wrong? 

Any help is most appreciated! Thanks!

**Comment by Nakul97** [comment]
Having the same issue! Lag with a tab bar controller.

**Comment by burakustn** [comment]
Same here is there any fix?

**Comment by stealdre** [comment]
Same issue here. I'm using a Snapchat like navigation in my app. That makes the user experience a bit bad. I don't think this lag comes from a huge amount of power needed. May be this lag is produced by a function with a completion handler...

**Comment by Jauzee** [comment]
Hi. Can someone of you share some example project to reproduce this issue?
