### ISSUE TITLE
FoldingCell.swift : pb_takeSnapshot : Guard being used incorrectly

### ISSUE THREAD

**Issue by kbMSU** [Ramotion/folding-cell#87]
I am using pod version 2.0.3 in a Swift-3 project.

Inside the pb_takeSnapshot method ( line 508 ) in the FoldingCell.swift file there is this block of code 

`
    let context = UIGraphicsGetCurrentContext();
    context!.translateBy(x: frame.origin.x * -1, y: frame.origin.y * -1)
    
    guard let currentContext = UIGraphicsGetCurrentContext() else {
      return nil
    }
`

Here the guard for UIGraphicsGetCurrentContext() is being called AFTER the same method is already used above it. This results in the context being nil sometimes so the line "context!.translateBy ....." fails.

The above is called when a user clicks on a cell to take it from a closed to an open state.

`cell.selectedAnimation(true, animated: true, completion: nil)` is the line called from the TableViewController ( as instructed in your Readme.md ) that eventually calls the buggy code above.

**Comment by Jauzee** [comment]
@kbMSU thank you!
