### ISSUE TITLE
Fold the cell when I press the button.

### ISSUE THREAD

**Issue by Joanii** [Ramotion/folding-cell#88]
How can I fold the cell when I press a button? Because at you example the cell I folded every time I press somewhere on it.

Thank you.

**Comment by Jauzee** [comment]
@Joanii maybe there is no issue for you now, but for those who have question as your's:

Assume we have some button inside of cell and we have `expandedIndexPath` class property in our view controller. We'll need to store `indexPath` of expanded cell inside of `didSelectRowAt indexPath`.

```swift
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
  expandedIndexPath = indexPath
}
```

And when button is pressed, we'll need to collapse expanded cell:

```swift
func buttonPressed(_ sender: UIButton) {
  guard
    let path = expandedIndexPath,
    let foldingCell = tableView.cellForRow(at: path) as? FoldingCell else { return }
  foldingCell.selectedAnimation(false, animated: true, completion: nil)
  cellHeights[path.row] = kCloseCellHeight

  UIView.animate(withDuration: 0.3, delay: 0, options: .curveEaseOut, animations: { () -> Void in
    tableView.beginUpdates()
    tableView.endUpdates()
  }, completion: nil)
}
```

**Comment by isaacraja15** [comment]
im using this code but animation not work 
 guard
            let path = self.expandedIndexPath,
            let foldingCell = self.tableView.cellForRow(at: path) as? FoldingCell else { return }
        foldingCell.setSelected(false, animated: true)
        self.cellHeights[path.row] = Const.closeCellHeight
        UIView.animate(withDuration: 0.3, delay: 0, options: .curveEaseOut, animations: { () -> Void in
            self.tableView.beginUpdates()
            self.tableView.endUpdates()
        }, completion: nil)

**Comment by isaacraja15** [comment]
thank !
i found it 

 // guard
                            let path = self.expandedIndexPath
                            // let foldingCell = self.tableView.cellForRow(at: path) as? FoldingCell else { return }
                            let cell = self.tableView.cellForRow(at: path!) as! DemoCell
                            //let cellIsCollapsed = cellHeights[path.row] == Const.closeCellHeight
                            if cell.isAnimating() {
                                return
                            }
                            self.cellHeights[path!.row] = Const.closeCellHeight
                            cell.unfold(false, animated: true, completion: nil)
                            
                            UIView.animate(withDuration: 0.8, delay: 0, options: .curveEaseOut, animations: { () -> Void in
                                self.tableView.beginUpdates()
                                self.tableView.endUpdates()
                                // tableView.reloadData()
                            }, completion: nil)
