### ISSUE TITLE
Not unfolding or folding correctly

### ISSUE THREAD

**Issue by O-mkar** [Ramotion/folding-cell#92]
Here is the example video
https://youtu.be/nCP_dyJ_lBU
Can you tell me why animation is not correct what is the problem is it a bug?

**Comment by O-mkar** [comment]
This issue is only faced after using **fromView.snapshotView(afterScreenUpdates: true)**

**Comment by chiformihai** [comment]
@O-mkar I'm having the same issue after using **snapshotView(afterScreenUpdates: true)**

**Comment by Jauzee** [comment]
It is not related to `FoldingCell` directly.
