### ISSUE TITLE
Change cell height on animation

### ISSUE THREAD

**Issue by spogatetz8386** [Ramotion/folding-cell#95]
I may have implemented it incorrectly but my cells are very large even when they are not expanded. Is there a way to have them initially be small, just a title, then expand to the height of the container view after it is clicked?

Here is a picture of what is happening:

![screen shot 2017-02-10 at 4 26 50 pm](https://cloud.githubusercontent.com/assets/21247362/22846587/d0533daa-efad-11e6-8fc6-9149c4d35b25.png)

![screen shot 2017-02-10 at 4 28 11 pm](https://cloud.githubusercontent.com/assets/21247362/22846624/fb9fceba-efad-11e6-9378-d293ccf6450a.png)

As you can see the height of the cell is fixed but I want to change it dynamically.

**Comment by Jauzee** [comment]
@spogatetz8386 please check your expanding/collapsing logic & ensure that you update values of `cellHeights` array.

**Comment by IOSDeveloperProgrammer** [comment]
@spogatetz8386  In my side container view not displaying in cell when i was click on it. but cell is expanded. help me out this issue ?
