### ISSUE TITLE
The Docs are not clear

### ISSUE THREAD

**Issue by Hsanka6** [Ramotion/folding-cell#97]
I followed the documentation but I'm having issues with nothing showing up on the ui tableviewcontroller

**Comment by Olympiloutre** [comment]
You shouldn't rely on the documentation, it's deprecated (it seems) 
You better download the repo, unzip it, open it with XCode. From there, read the doc AND the code simultaneosly, you'll be able to find out what's important and what is not, just mimic it to your own viewController and its fine.

**Comment by ober01** [comment]
look for example project https://github.com/Ramotion/folding-cell/tree/master/FoldingCell/FoldingCell-Demo
