### ISSUE TITLE
Swift 2.2 version

### ISSUE THREAD

**Issue by rifroze** [Ramotion/folding-cell#99]
I am not sure which version is compatible with swift 2.2, can someone help me with this?
Thanks in advance

**Comment by l0l0c0ding** [comment]
I have solved 1-2 issues in the programmatic example for SWIFT 3.0.
Following migration of the source code by XCode, I had to rework a bit the constraints setting of the containerView and foregroundView. Happy to share the details.

**Comment by Juriv** [comment]
we don't support swift 2.2 so I recommend to use the latest one
